# Generated by Django 3.0.3 on 2020-03-08 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redeem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeem', to=settings.AUTH_USER_MODEL),
        ),
    ]
